In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

###Read File and verify

In [ ]:
#upload dataset

from google.colab import files

uploaded = files.upload()

Saving ecommerce_sales.csv to ecommerce_sales.csv

In [ ]:
#read dataset

df = pd.read_csv("ecommerce_sales.csv", encoding = 'latin1')

In [ ]:
#check data

df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,No,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,No,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,No,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,No,13.88,2.74,1.15,39,Male

In [ ]:
df.tail()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
34495,O134495,C13553,P231412,Fashion,10.44,0.20,1,Debit Card,2025-08-13,3,North,No,8.35,3.04,-0.12,23,Female
34496,O134496,C11349,P218266,Beauty,4.79,0.10,5,Debit Card,2023-12-04,6,South,Yes,21.56,3.37,6.33,61,Female
34497,O134497,C12986,P204345,Electronics,323.64,0.00,5,Credit Card,2025-02-01,6,East,No,1618.20,12.18,182.00,41,Female
34498,O134498,C17196,P217644,Home,23.09,0.05,1,Credit Card,2024-03-27,6,East,No,21.94,5.61,0.53,27,Female
34499,O134499,C13330,P207047,Home,76.84,0.00,1,Debit Card,2025-09-11,6,East,No,76.84,7.57,13.95,19,Male

In [ ]:
print(f"No of rows : {df.shape[0]}")

print(f"No of columns : {df.shape[1]}")

No of rows : 34500
No of columns : 17

In [ ]:
#basic information


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            34500 non-null  object
 1   customer_id         34500 non-null  object
 2   product_id          34500 non-null  object
 3   category            34500 non-null  object
 4   price               34500 non-null  float64
 5   discount            34500 non-null  float64
 6   quantity            34500 non-null  int64
 7   payment_method      34500 non-null  object
 8   order_date          34500 non-null  object
 9   delivery_time_days  34500 non-null  int64
 10  region              34500 non-null  object
 11  returned            34500 non-null  object
 12  total_amount        34500 non-null  float64
 13  shipping_cost       34500 non-null  float64
 14  profit_margin       34500 non-null  float64
 15  customer_age        34500 non-null  int64
 16  customer_gender     34500 non-null  object
dtypes: float64(5), int64(3), object(9)
memory usage: 4.5+ MB

###Check missing values

In [ ]:
#missing values

df.isnull().sum()

order_id              0
customer_id           0
product_id            0
category              0
price                 0
discount              0
quantity              0
payment_method        0
order_date            0
delivery_time_days    0
region                0
returned              0
total_amount          0
shipping_cost         0
profit_margin         0
customer_age          0
customer_gender       0
dtype: int64

###Check for duplicates

In [ ]:
#checking duplicates

df.duplicated().sum()

np.int64(0)

In [ ]:
#unique items in each column
df.nunique()

order_id              34500
customer_id            7903
product_id            24912
category                  7
price                 17274
discount                  6
quantity                  5
payment_method            6
order_date              731
delivery_time_days       10
region                    5
returned                  2
total_amount          18800
shipping_cost          1304
profit_margin          9603
customer_age             52
customer_gender           3
dtype: int64

###Check column names

In [ ]:
#Check column names

df.columns.tolist()

['order_id',
 'customer_id',
 'product_id',
 'category',
 'price',
 'discount',
 'quantity',
 'payment_method',
 'order_date',
 'delivery_time_days',
 'region',
 'returned',
 'total_amount',
 'shipping_cost',
 'profit_margin',
 'customer_age',
 'customer_gender']

In [ ]:
## convert order_date to proper datetime

df["order_date"] = pd.to_datetime(df["order_date"])

###Descriptive Statistics

In [ ]:
df.describe()

,price,discount,quantity,order_date,delivery_time_days,total_amount,shipping_cost,profit_margin,customer_age
count,34500.000000,34500.000000,34500.000000,34500,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000
mean,119.391632,0.049291,1.490725,2024-09-13 13:39:17.843478272,4.814203,170.008494,6.152120,28.116505,43.474377
min,1.010000,0.000000,1.000000,2023-09-12 00:00:00,3.000000,0.820000,0.000000,-6.200000,18.000000
25%,16.690000,0.000000,1.000000,2024-03-14 00:00:00,4.000000,19.710000,4.420000,1.500000,31.000000
50%,45.660000,0.000000,1.000000,2024-09-16 00:00:00,5.000000,56.820000,6.090000,10.550000,43.000000
75%,130.950000,0.100000,2.000000,2025-03-17 00:00:00,6.000000,168.530000,7.830000,33.132500,56.000000
max,2930.470000,0.300000,5.000000,2025-09-11 00:00:00,13.000000,12931.800000,15.650000,1536.170000,69.000000
std,195.620477,0.069894,0.932270,NaN,1.242141,357.503014,2.389539,53.352947,14.980682

In [ ]:
df.describe(include = 'object')

,order_id,customer_id,product_id,category,payment_method,region,returned,customer_gender
count,34500,34500,34500,34500,34500,34500,34500,34500
unique,34500,7903,24912,7,6,5,2,3
top,O134499,C16704,P200645,Fashion,Credit Card,South,No,Female
freq,1,13,7,6254,12170,7584,32597,16818

In [ ]:
#verifying the total amount
df["calculated_amount"] = (
    df["price"] * df["quantity"] * (1 - df["discount"])
)

In [ ]:
df[["price", "quantity", "discount", "total_amount", "calculated_amount"]].head(10)

    price  quantity  discount  total_amount  calculated_amount
0  164.08         1      0.15        139.47           139.4680
1   24.73         1      0.00         24.73            24.7300
2  175.58         1      0.05        166.80           166.8010
3   63.67         1      0.00         63.67            63.6700
4   16.33         1      0.15         13.88            13.8805
5   53.91         2      0.10         97.04            97.0380
6  266.50         1      0.00        266.50           266.5000
7    9.98         1      0.00          9.98             9.9800
8    6.61         1      0.05          6.28             6.2795
9   10.91         1      0.00         10.91            10.9100

In [ ]:
df.drop('calculated_amount', axis=1, inplace = True)

###Since we have not made any alterations we will use the same dataset for power BI